### ISSUE TITLE
Functionality to allow cookbook repo management to be disabled via data bag.

### ISSUE THREAD

**Issue by ericv5** [chef-cookbooks/yum-erlang_solutions#5]
At my company we don't allow servers to have outgoing internet access.  We have our yum repos mirrored internally and managed by our own chef cookbooks (which point to our internal mirrors).  

We do need this cookbook to satisfy dependancies with other OpenStack cookbooks.  But we would like the ability to disable it via data bag.  The "yum-epel" cookbooks currently offers this (https://github.com/chef-cookbooks/yum-epel):

attributes/epel.rb:
default['yum']['epel']['managed'] = true

receipes/default.rb:
  if node['yum'][repo]['managed']
  # then configure the repo.

The data bag section to disable would look like this:
    "override_attributes": {
      "yum": {
        "epel": {
             "managed": false
           }
      },

Thank you

**Comment by dpetzel** [comment]
Did you mean roles (rather than data bags)? I'm not sure the linked PR does anything to assist with the use of data bags.

We have the same use case as you do, and there are two options you can leverage without any changes:

1) You can set `node['yum']['erlang_solutions']['enabled']` to false. This will *manage* the file as in deploy it to the filesystem, however the repo will be disabled so your node's should not hit the internet. I'm curious why anyone would want to "not manage" the file allowing hand editing of the file to take place? I would think (but admit there are always use cases I didn't consider) that managing the file and disabling it would be preferable to not managing the file at all?

2) (This is how we do it). Rather than disable the repo we set `node['yum']['erlang_solutions']['baseurl']` to the value of our internal mirror via a wrapper cookbook (you could do it just as easily via roles). For us this was a very light lift and ensures any cookbooks that call this one, get the .repo file configured for our internal mirror, so even if someone were to manually pass the --enablerepo flag, there are going to hit our internal mirror.

**Comment by someara** [comment]
The "managed" vs "enabled" thing came from people not wanting to makecache
on all the testing, debug, source, etc repositories that come with the
other yum-* cookbooks.

For example, yum-centos comes with extras, updates, etc
https://github.com/chef-cookbooks/yum-centos/tree/master/attributes

yum-ius comes with quite a bit as well.
https://github.com/chef-cookbooks/yum-ius/tree/master/attributes

yum_repository will makecache on every .repo repair, regardless if they're
enabled or not.
https://github.com/chef-cookbooks/yum/blob/master/providers/repository.rb#L49

When moving a repository state from "enabled" to "disabled", that makecache
still needs to be ran.

The solution was to put a "managed" with a false state on all the
testing/debug/whatever repositories shipped in the yum-* series.

yum-erlang_solutions is the odd duck out since it only ships one
repository... so it may not be apparent just by looking this cookbook in
isolation.

**Comment by someara** [comment]
You can point this repository at internal mirrors by manipulating the 
node['yum-erlang_solutions']['mirrorlist'] and node['yum-erlang_solutions']['baseurl'] attributes.

"managed" doesn't do what you think it does here. Explanation in the above comments.
Closing.
